name: base
channels:
  - conda-forge
  - defaults
  - damianavila82
  - anaconda
  - pytorch
dependencies:
  - nodejs
  - python
  - ipykernel
  - ipympl
  - jupyter
  - jupyterlab
  - jupyter_contrib_nbextensions
  - matplotlib
  - cython
  - numpy
  - root
  - root_numpy
  - scipy
  - pandas
  - xlrd
  - openpyxl
  - sympy
  - nbconvert
  - nbstripout
  - ipyvolume
  - ipywidgets
  - seaborn
  - bokeh
  - altair
  - uncertainties
  - sphinx
  - rise
  - pyne=0.5.11=py36_blas_openblas_0
  - scikit-learn
  - pillow
  - xarray
  - dask
  - netCDF4
  - bottleneck
  - pytorch
  - torchvision
  - cudatoolkit=10.2
  - pip
  - pip:
    #- pyyaml
    - pysrim
    - rootpy
    - autograd
    - tensorflow
    - Keras
    - Theano
